2019-03-18 21:59:07,081 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 301859ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 22:04:50,031 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302935ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 22:10:12,985 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302940ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 22:15:55,980 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302971ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 22:21:38,944 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302945ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 22:27:21,925 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302963ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:02:57,747 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 2115807ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:08:40,806 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302996ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:14:23,816 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302999ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:19:46,763 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302940ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:25:29,732 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302954ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:31:12,689 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302939ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-18 23:40:54,124 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 561419ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 01:41:52,925 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 7218764ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 01:47:35,891 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302957ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 01:53:23,941 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 308027ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 01:58:46,907 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302950ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 02:10:12,873 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302990ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 02:15:35,807 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302923ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:16:34,653 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 7218827ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:22:17,657 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302956ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:27:41,116 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 303433ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:33:24,081 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302936ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:39:07,055 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302947ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:44:50,023 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302950ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 04:50:12,969 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302929ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 06:51:11,876 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 7218894ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 06:56:54,870 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302946ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 07:02:17,820 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302937ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 07:08:00,783 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302951ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 07:19:07,252 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 303391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 07:24:50,196 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302909ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 09:25:49,148 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 7218935ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 09:31:32,114 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302955ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 09:36:55,056 ERROR 37188 nodejs.ClusterClientNoResponseError: client no response in 302928ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37188
hostname: wangyideMacBook-Pro.local

2019-03-19 11:25:05,271 ERROR 37930 [-/127.0.0.1/-/14ms GET /wx/test2] nodejs.ReferenceError: xml is not defined
    at TestWx.test3 (/Users/wangyi/node/yoo/wx/app/controller/wx/wxPro.js:79:24)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:45:18)
    at /Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at /Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/wangyi/node/yoo/wx/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wangyi/node/yoo/wx/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)

pid: 37930
hostname: wangyideMacBook-Pro.local

2019-03-19 11:25:07,782 ERROR 37930 [-/127.0.0.1/-/2ms GET /wx/test2] nodejs.ReferenceError: xml is not defined
    at TestWx.test3 (/Users/wangyi/node/yoo/wx/app/controller/wx/wxPro.js:79:24)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:45:18)
    at /Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at /Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/wangyi/node/yoo/wx/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wangyi/node/yoo/wx/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)

pid: 37930
hostname: wangyideMacBook-Pro.local

2019-03-19 21:01:28,670 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 301593ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 00:56:48,266 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 7212603ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 02:57:07,916 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 7219353ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 04:57:28,596 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 7220625ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 06:57:49,248 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 7220635ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 08:30:10,866 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 5541598ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 09:40:46,071 ERROR 38021 nodejs.ClusterClientNoResponseError: client no response in 4235195ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wangyi/node/yoo/wx/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 38021
hostname: wangyideMacBook-Pro.local

2019-03-20 11:56:21,069 ERROR 39642 [-/127.0.0.1/-/3ms GET /volvo/info] nodejs.TypeError: Cannot read property 'H5VolvoUser' of undefined
    at new VolvoService (/Users/wangyi/node/yoo/wx/app/service/volvo.js:10:32)
    at getInstance (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/context_loader.js:92:18)
    at ClassLoader.get (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/context_loader.js:27:22)
    at VolvoController.getInfo (/Users/wangyi/node/yoo/wx/app/controller/h5/volvo.js:9:32)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:45:18)
    at /Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at /Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/wangyi/node/yoo/wx/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wangyi/node/yoo/wx/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)

pid: 39642
hostname: wangyideMacBook-Pro.local

2019-03-20 11:57:04,626 ERROR 39658 [-/127.0.0.1/-/14ms GET /zfb/pay] nodejs.ReferenceError: options is not defined
    at AlipayService.request (/Users/wangyi/node/yoo/wx/app/service/alipay.js:19:45)
    at AlipayService.tradePay (/Users/wangyi/node/yoo/wx/app/service/alipay.js:31:17)
    at PayMenmZFB.pay (/Users/wangyi/node/yoo/wx/app/controller/zfb/payment.js:12:39)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:45:18)
    at /Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at /Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/wangyi/node/yoo/wx/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wangyi/node/yoo/wx/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/xframe.js:7:11)

pid: 39658
hostname: wangyideMacBook-Pro.local

2019-03-20 11:57:45,575 ERROR 39658 [-/127.0.0.1/-/3ms GET /zfb/pay?authCode=280460745655648893] nodejs.ReferenceError: options is not defined
    at AlipayService.request (/Users/wangyi/node/yoo/wx/app/service/alipay.js:19:45)
    at AlipayService.tradePay (/Users/wangyi/node/yoo/wx/app/service/alipay.js:31:17)
    at PayMenmZFB.pay (/Users/wangyi/node/yoo/wx/app/controller/zfb/payment.js:12:39)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/wangyi/node/yoo/wx/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:45:18)
    at /Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:44:32)
    at /Users/wangyi/node/yoo/wx/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/wangyi/node/yoo/wx/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wangyi/node/yoo/wx/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/wangyi/node/yoo/wx/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/wangyi/node/yoo/wx/node_modules/egg-security/lib/middlewares/xframe.js:7:11)

pid: 39658
hostname: wangyideMacBook-Pro.local

